use anyhow::{anyhow, Result};
use nix::sys::signal::{self, Signal};
use nix::unistd::Pid;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::Duration;

/// Start the `i2pd` binary.
pub fn start_i2p(
    data_dir: &str,
    http_port: u16,
    https_port: u16,
    socks_port: u16,
    native_lib_dir: &str,
) -> Result<Pid> {
    let i2pd_bin = Path::new(native_lib_dir).join("libi2pd.so");

    if !i2pd_bin.exists() {
        return Err(anyhow!("i2pd binary not found at {}", i2pd_bin.display()));
    }

    let conf_dir = Path::new(data_dir).join("conf");
    std::fs::create_dir_all(&conf_dir)?;

    let config = build_i2pd_config(data_dir, http_port, https_port, socks_port);
    let config_path = conf_dir.join("i2pd.conf");
    std::fs::write(&config_path, config)?;

    let tunnels_path = conf_dir.join("tunnels.conf");
    if !tunnels_path.exists() {
        std::fs::write(&tunnels_path, "")?;
    }

    let child = Command::new(&i2pd_bin)
        .arg(format!("--conf={}", config_path.display()))
        .arg(format!("--tunconf={}", tunnels_path.display()))
        .arg(format!("--datadir={data_dir}"))
        .arg("--daemon=false")
        .env("LD_LIBRARY_PATH", native_lib_dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| anyhow!("Failed to spawn i2pd: {e}"))?;

    let pid = Pid::from_raw(child.id() as i32);

    // i2pd takes longer to initialize
    std::thread::sleep(Duration::from_millis(1000));

    match nix::sys::signal::kill(pid, None) {
        Ok(_) => {
            log::info!("i2pd started with PID {pid}");
            Ok(pid)
        }
        Err(_) => Err(anyhow!("i2pd exited immediately")),
    }
}

fn build_i2pd_config(data_dir: &str, http_port: u16, https_port: u16, socks_port: u16) -> String {
    format!(
        r#"# i2pd configuration generated by ZzZ VPN
loglevel = warn
datadir = {data_dir}

[http]
enabled = true
address = 127.0.0.1
port = {http_port}

[httpproxy]
enabled = true
address = 127.0.0.1
port = {https_port}

[socksproxy]
enabled = true
address = 127.0.0.1
port = {socks_port}

[sam]
enabled = false

[bob]
enabled = false

[i2cp]
enabled = false

[upnp]
enabled = false

[reseed]
verify = true

[limits]
transittunnels = 2500
"#
    )
}

/// Stop i2pd gracefully.
pub fn stop_i2p(pid: Pid) {
    log::info!("Stopping i2pd PID {pid}");
    let _ = signal::kill(pid, Signal::SIGTERM);
    std::thread::sleep(Duration::from_millis(2000));
    if nix::sys::signal::kill(pid, None).is_ok() {
        let _ = signal::kill(pid, Signal::SIGKILL);
    }
}
